<a href="https://colab.research.google.com/github/lakshlahoti15/MFDS_Assignment/blob/main/MDS_WEEK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#installing numpy library
pip install numpy

In [ ]:
import numpy as np
#checking the version of the numpy
print(np.__version__)

2.0.2


### Comparing Python List vs. NumPy Array Performance

In [ ]:
import time
import numpy as np

# Define the size of the array/list for performance comparison
size = 10000000 # 10 million elements

# --- Python List ---
# Create a Python list with a range of numbers
python_list = list(range(size))

# Record the start time for list sum calculation
start_time_list = time.time()
# Calculate the sum of elements in the Python list
sum_list = sum(python_list)
# Record the end time for list sum calculation
end_time_list = time.time()

# Calculate the time taken for list sum
time_taken_list = end_time_list - start_time_list
# Print the time taken and the sum for the Python list
print(f"Python List Sum Time: {time_taken_list:.6f} seconds")
print(f"Sum of Python List: {sum_list}")

Python List Sum Time: 0.103252 seconds
Sum of Python List: 49999995000000


In [ ]:
# --- NumPy Array ---
# Create a NumPy array with a range of numbers
numpy_array = np.arange(size)

# Record the start time for NumPy array sum calculation
start_time_numpy = time.time()
# Calculate the sum of elements in the NumPy array
sum_numpy = np.sum(numpy_array)
# Record the end time for NumPy array sum calculation
end_time_numpy = time.time()

# Calculate the time taken for NumPy array sum
time_taken_numpy = end_time_numpy - start_time_numpy
# Print the time taken and the sum for the NumPy array
print(f"NumPy Array Sum Time: {time_taken_numpy:.6f} seconds")
print(f"Sum of NumPy Array: {sum_numpy}")

NumPy Array Sum Time: 0.006829 seconds
Sum of NumPy Array: 49999995000000


### Comparing Python List vs. NumPy Array Memory Usage

In [ ]:
import sys
import numpy as np

# Define the size for memory usage comparison
size = 10000000

# Create a Python list for memory calculation
python_list_mem = list(range(size))

# Get the memory size of the Python list object itself (overhead)
list_overhead = sys.getsizeof(python_list_mem)

# Print memory usage details for Python list
print(f"Memory of Python List (object overhead only): {list_overhead} bytes")
print(f"Approximate memory for 10 million Python integer objects (each ~28 bytes): {size * 28} bytes")
print(f"Total estimated memory for Python List (including elements): {list_overhead + (size * 28)} bytes")

Memory of Python List (object overhead only): 80000056 bytes
Approximate memory for 10 million Python integer objects (each ~28 bytes): 280000000 bytes
Total estimated memory for Python List (including elements): 360000056 bytes


In [ ]:
# Create a NumPy array for memory calculation
numpy_array_mem = np.arange(size)

# Get the memory size of the NumPy array in bytes
numpy_memory = numpy_array_mem.nbytes

# Print memory usage for NumPy array
print(f"Memory of NumPy Array: {numpy_memory} bytes")

Memory of NumPy Array: 80000000 bytes


In [ ]:
#creating a list
list1=[81,2,3,4,5]

In [ ]:
#checking the type of the list
type(list1)

list

In [ ]:
#create the array from list1
arr1=np.array(list1)

In [ ]:
# Print the elements of the array
print(*arr1)

81 2 3 4 5


In [ ]:
# Check the type of arr1
type(arr1)

numpy.ndarray

In [ ]:
#dimension of the array
print(arr1.ndim)

1


In [ ]:
#the datatype of the array
arr1.dtype

dtype('int64')

In [ ]:
# Get the name of the data type
arr1.dtype.name

'int64'

In [ ]:
# Get the total number of elements in the array
arr1.size

5

In [ ]:
# Get the shape of the array
arr1.shape

(5,)

In [ ]:
# Get the total bytes consumed by the array elements
arr1.nbytes

40

In [ ]:
# Create a tuple
tuple1=(81,2,3,5)

In [ ]:
# Check the type of tuple1
type(tuple1)

tuple

In [ ]:
# Create a tuple with a single element
tuple2=(1,)
# Check the type of tuple2
type(tuple2)

tuple

In [ ]:
# Create a NumPy array from the tuple
arr2=np.array(tuple1)

In [ ]:
# Print the elements of arr2
print(arr2)

[81  2  3  5]


In [ ]:
# Get the dimension of arr2
arr2.ndim

1

In [ ]:
# Create a list of lists
list3=[[81,2],[3,4]]

In [ ]:
# Create a NumPy array from the list of lists
matrix=np.array(list3)

In [ ]:
# Check the type of matrix
type(matrix)

numpy.ndarray

In [ ]:
# Print the matrix
print(matrix)

[[81  2]
 [ 3  4]]


In [ ]:
# Get the dimension of the matrix
matrix.ndim

2

In [ ]:
# Get the shape of the matrix
matrix.shape

(2, 2)

In [ ]:
# Get the total number of elements in the matrix
matrix.size

4

In [ ]:
# Get the total bytes consumed by the matrix elements
matrix.nbytes

32

In [ ]:
# Flatten the matrix into a 1D array
matrix.flatten()

array([81,  2,  3,  4])

In [ ]:
# Flatten the matrix into a 1D array
matrix.ravel()

array([81,  2,  3,  4])

In [ ]:
# Create a 1D NumPy array
arr4=np.array([81,2,3,4])

In [ ]:
# Print arr4
print(arr4)

[81  2  3  4]


In [ ]:
# Create a 2D NumPy array
arr5=np.array([[81,2],[3,4]])

In [ ]:
# Create a NumPy matrix from a list of lists
matrix1=np.matrix([[81,2],[3,4],[5,6]])

In [ ]:
# Print matrix1
print(matrix1)

[[81  2]
 [ 3  4]
 [ 5  6]]


In [ ]:
# Create an array with values from 1 to 100 (exclusive of 101)
arr_1_to_100 = np.arange(1, 101)
# Print the created array
print(arr_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
# Create an array with values from 1 to 99 (exclusive of 100)
arr6=np.arange(1,100)

In [ ]:
# Create an array with values from 0 to 98 with a step of 2
arr6 = np.arange(0, 100,2)
# Print the array
print(arr6)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
# Create an array with values from 0 to 9
matrix3=np.arange(0,10)
# Reshape the 1D array into a 2D array (2 rows, 5 columns)
matrix3.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Flatten matrix3 back into a 1D array
matrix3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a 3x3 array filled with ones, with integer data type
a=np.ones([3,3],dtype='int')

In [ ]:
# Print the array 'a'
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# Attempt to access names of structured dtype fields (not applicable for simple int array)
a.dtype.names

In [ ]:
# Create a 3x3 array filled with the value 81
c=np.full([3,3],81)

In [ ]:
# Print the array 'c'
print(c)

[[81 81 81]
 [81 81 81]
 [81 81 81]]


In [ ]:
# Create a 3x3 identity matrix with integer data type
e=np.eye(3,dtype='int')

In [ ]:
# Print the identity matrix 'e'
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Create an array with 5 evenly spaced numbers between 0 and 1 (inclusive)
f=np.linspace(0,1,5)

In [ ]:
# Print the array 'f'
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create a 3x3 array with random floats between 0.0 and 1.0
x=np.random.random([3,3])

In [ ]:
# Print the array 'x'
print(x)

[[0.5398909  0.84460825 0.49708686]
 [0.98047652 0.4209369  0.32878289]
 [0.53671345 0.81838775 0.52763178]]


In [ ]:
arr8=np.arange(1,10)
print(arr8)
arr8[0]=81 # Modify the first element of the array
print(arr8)
print(arr8.max())
print(arr8.min())

[1 2 3 4 5 6 7 8 9]
[81  2  3  4  5  6  7  8  9]
81
2
